/**
 * Leverantörer the customer commonly wants to cancel — Swedish telecom,
 * energy and alarm providers plus the media/web/directory agencies that
 * make up the bulk of mediacleaning cases.
 *
 * Each entry carries the notice address so picking a supplier fills in the
 * required "Uppsägningsadress" instead of leaving the seller to look it up.
 * Anything outside this list is entered by hand via "Annan leverantör".
 *
 * Names are unique: "Advago AB" and "Advago AB (EasyPartner)" share an
 * address but are separate brands, so both stay in the picker.
 */
export const KNOWN_SUPPLIERS: { name: string; noticeAddress: string }[] = [
  { name: "AdAccess AB", noticeAddress: "Box 392, 501 13 Borås" },
  { name: "Addictive Group Media AB", noticeAddress: "Gustavslundsvägen 141, 167 51 Bromma" },
  { name: "Advago AB", noticeAddress: "Stora Gatan 11, 731 31 Köping" },
  { name: "Advago AB (EasyPartner)", noticeAddress: "Stora Gatan 11, 731 31 Köping" },
  { name: "AIM Partner AB (556849-5906)", noticeAddress: "Rosenborgsgatan 12, 169 74 Solna" },
  { name: "AJT Sweden AB", noticeAddress: "Pomonagatan 1, 169 73 Solna" },
  { name: "Allonge AB", noticeAddress: "Box 696 Kocksg 49, 116 29 Stockholm" },
  { name: "Apporté AB", noticeAddress: "Erik Dahlbergsgatan 23 Lgh 1101, 115 32 Stockholm" },
  { name: "Bolagskollen AB (Tryggaval.se)", noticeAddress: "Karlavägen 18 BV, 114 31 Stockholm" },
  { name: "Bovra Technologies AB", noticeAddress: "Engelbrektsgatan 5, 114 32 Stockholm" },
  { name: "BraByggare Sverige AB", noticeAddress: "Sankt Eriksgatan 46A, 112 34 Stockholm" },
  { name: "Branschvinnare i Sverige AB (Sverigesvinnare.se)", noticeAddress: "Alviksvägen 25, 167 17 Bromma" },
  { name: "Commercial and Brands Sweden AB", noticeAddress: "Mailbox 1521, 411 41 Göteborg" },
  { name: "Connected CMS Webbyrå AB (cms.se)", noticeAddress: "Box 55157, 501 14 Borås" },
  { name: "Contactmedia Sverige AB", noticeAddress: "Krokslätts Fabriker 30, 431 37 Mölndal" },
  { name: "Dorunner AB", noticeAddress: "Karlavägen 50, 114 40 Stockholm" },
  { name: "E.ON Energilösningar AB", noticeAddress: "205 09 Malmö" },
  { name: "Effektive Group Sverige AB", noticeAddress: "Varedsvägen 32, 504 64 Borås" },
  { name: "Eniro Group AB (Eniro.se)", noticeAddress: "Kistagången 12, 164 40 Kista" },
  { name: "FFSVEA AB (Förenade Företag)", noticeAddress: "Övägen 1, 216 14 Limhamn" },
  { name: "Fortum Markets AB", noticeAddress: "115 77 Stockholm" },
  { name: "Generaxion AB", noticeAddress: "Rosenborgsgatan 12, 169 74 Solna" },
  { name: "GodEl i Sverige AB", noticeAddress: "Box 121, 101 22 Stockholm" },
  { name: "Hittapunktse AB (Hitta.se)", noticeAddress: "Sankt Eriksgatan 121 D, 113 43 Stockholm" },
  { name: "INTENDIT AB", noticeAddress: "Nordenskiöldsgatan 4, 211 19 Malmö" },
  { name: "Internet.se Svenska AB", noticeAddress: "Gamlestadsvägen 1, 415 11 Göteborg" },
  { name: "JS Mediakonsulter AB", noticeAddress: "Faktorvägen 29, 922 31 Vindeln" },
  { name: "Kvalitetspartner Sverige AB", noticeAddress: "Vretenvägen 13, 171 54 Solna" },
  { name: "Mainztreet Media AB", noticeAddress: "Box 1128, 501 11 Borås" },
  { name: "Mediakonsult1 AB", noticeAddress: "Lilla Brogatan 11, 503 30 Borås" },
  { name: "Mediakonsulterna i Linköping AB", noticeAddress: "Klostergatan 5A, 582 23 Linköping" },
  { name: "Mediaproffs i Nässjö AB", noticeAddress: "Södra Skogsvägen 56, 571 39 Nässjö" },
  { name: "MEDIASE AB", noticeAddress: "Kocksgatan 49, 116 29 Stockholm" },
  { name: "Merinfo Sverige AB", noticeAddress: "Hulda Mellgrens Gata 11B, 421 32 Västra Frölunda" },
  { name: "Modhs Webbyrå AB", noticeAddress: "Östra Storgatan 50, 553 21 Jönköping" },
  { name: "No Sleep AB", noticeAddress: "Sjövikskajen 62, 117 57 Stockholm" },
  { name: "Nordens Hjältar Group AB", noticeAddress: "Box 387, 501 13 Borås" },
  { name: "Nordiska Webbyrån AB", noticeAddress: "Getängsvägen 22E, 504 68 Borås" },
  { name: "Nätvaro AB", noticeAddress: "Hemvärnsgatan 15, 171 54 Solna" },
  { name: "Offerta Group AB", noticeAddress: "Linnégatan 89, 115 23 Stockholm" },
  { name: "Partner i Norden AB", noticeAddress: "Ekbacksvägen 28, 16869 Bromma" },
  { name: "PEAO Webbyrå", noticeAddress: "Starrbäcksgatan 16, 172 74 Sundbyberg" },
  { name: "Project Art Sweden HB (skale.se)", noticeAddress: "Hantverksgatan 28, 302 42 Halmstad" },
  { name: "Reco Sverige AB", noticeAddress: "Vasagatan 15-17, 111 20 Stockholm" },
  { name: "Scrive AB", noticeAddress: "Grev Turegatan 11A, 114 46 Stockholm" },
  { name: "Sector Alarm AB", noticeAddress: "Box 121, 411 15 Göteborg" },
  { name: "Servicefinder Sverige AB", noticeAddress: "Stureplan 4C, 114 35 Stockholm" },
  { name: "Smartproduktion Sverige AB", noticeAddress: "Nedre Tjärna 309, 785 30 Gagnef" },
  { name: "Stilio Media AB", noticeAddress: "Kungsgatan 37, 111 56 Stockholm" },
  { name: "Svensk Annonsförmedling AB", noticeAddress: "Box 5250, 102 45 Stockholm" },
  { name: "Svenskt Bolagsindex AB", noticeAddress: "Box 441, 116 74 Stockholm" },
  { name: "Svenskt Bolagsindex AB (Årets Entreprenörer)", noticeAddress: "Box 441, 116 74 Stockholm" },
  { name: "Tele2 Sverige AB", noticeAddress: "Box 62, 164 94 Kista" },
  { name: "Telenor Sverige AB", noticeAddress: "116 88 Stockholm" },
  { name: "Telia Sverige AB", noticeAddress: "Box 50077, 104 05 Stockholm" },
  { name: "Torggruppen AB", noticeAddress: "Kristian IV:s Väg 3 9tr, 302 50 Halmstad" },
  { name: "Tre (Hi3G Access AB)", noticeAddress: "Box 30213, 104 25 Stockholm" },
  { name: "UC Affärsinformation AB (allabolag.se)", noticeAddress: "Klarabergsviadukten 63, 111 64 Stockholm" },
  { name: "Vattenfall Kundservice", noticeAddress: "162 87 Stockholm" },
  { name: "Verisure Sverige AB", noticeAddress: "Box 121, 581 02 Linköping" },
  { name: "Viewton AB (Connect Studios Sweden)", noticeAddress: "Polhemsgatan 10, 126 30 Stockholm" },
  { name: "VIZIBLY AB", noticeAddress: "Box 1206, 501 12 Borås" },
  { name: "VM Group AB", noticeAddress: "Köpmangatan 29B, 831 30 Östersund" },
  { name: "W Landslaget AB", noticeAddress: "Furusundsgatan 8, 115 37 Stockholm" }
];
